from animais import *

peixe1 = Peixe("Nemo", 0.90,"água doce")
print(peixe1)
print('-='*20)
peixe2 = Peixe("Dori", 0.50,"água doce")
print(peixe2)
print('-='*20)
peixe3 = Peixe("Bauru", 0.40,"água salgada")
print(peixe3)
print('-='*20)
cachorro1 = Cachorro("Hulk", 12, "Vira-lata")
print(cachorro1)
print('-='*20)
cachorro2 = Cachorro("Spaik", 8, "Pastor Alemão")
print(cachorro2)
print('-='*20)
cachorro3 = Cachorro("Pretinha", 10, "Fila")
print(cachorro3)
print('-='*20)
